---
- name: Creation VMs
  hosts: localhost
  connection: local

  vars_prompt:    
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
      private: yes  
  tasks:
    - vsphere_guest:    
        validate_certs: false
        vcenter_hostname: esxvc-ga-msdc01.ds.dtveng.net
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"      
        guest: "{{ item }}"
        state: present       
        vm_extra_config:
          notes: notes
        vm_disk:
          disk1:
            size_gb: 25
            type: thin
            datastore: 7400-esxvrtdvi-msdc03
        vm_nic:
          nic1:
            type: vmxnet3
            network: dvS2-Dev-vlan74
            network_type: standard
        vm_hardware:
          memory_mb: 1024
          num_cpus: 1
          osid: centos64Guest
          scsi: paravirtual
        esxi:
          datacenter: MSDC
          hostname: esxvrtdv-msdc34.ds.dtveng.net
      with_items:
        - OlehVM01
        - OlehVM02
        - OlehVM03